apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kc-ui.fullname" . }}
  labels:
    app: {{ template "kc-ui.name" . }}
    chart: {{ template "kc-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kc-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kc-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.servicePort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
        ports:
        - containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: APPLICATION_NAME
            value: "{{ .Release.Name }}"
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
          - name: FLEETMS_SERVICE_HOST
            value: "{{ .Values.application.fleetServiceHost }}"
          - name: FLEETMS_SERVICE_PORT
            value: "{{ .Values.application.fleetServicePort }}"
          - name: ORDERCOMMANDMS_SERVICE_HOST
            value: "{{ .Values.application.orderCommandServiceHost }}"
          - name: ORDERCOMMANDMS_SERVICE_PORT
            value: "{{ .Values.application.orderCommandServicePort }}"
          - name: ORDERQUERYMS_SERVICE_HOST
            value: "{{ .Values.application.orderQueryServiceHost }}"
          - name: ORDERQUERYMS_SERVICE_PORT
            value: "{{ .Values.application.orderQueryServicePort }}"
          - name: VOYAGESMS_SERVICE_HOST
            value: "{{ .Values.application.voyageServiceHost }}"
          - name: VOYAGESMS_SERVICE_PORT
            value: "{{ .Values.application.voyageServicePort }}"
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.eventstreams.brokersConfigMap }}"
                key: brokers
          - name: PROBLEM_TOPIC
            value: "{{ .Values.kafka.bluewaterProblemTopicName }}"
          - name: SHIP_TOPIC
            value: "{{ .Values.kafka.bluewaterShipTopicName }}"
          {{- if .Values.eventstreams.enabled }}
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.eventstreams.apikeyConfigMap }}"
                key: binding
          {{- if .Values.eventstreams.caPemFileRequired }}
          - name: CERTS_ENABLED
            value : "true"
          - name: KAFKA_CERT_PATH
            value : "{{ .Values.eventstreams.caPemFilePath }}/{{ .Values.eventstreams.caPemFileName }}"
          {{- end }}
          {{- end}}
        {{- if .Values.eventstreams.caPemFileRequired }}
        volumeMounts:
          - mountPath: "{{ .Values.eventstreams.caPemFilePath }}"
            name: eventstreams-pem-certificate
            readOnly: true
        {{- end }}
      {{- if .Values.eventstreams.caPemFileRequired }}
      volumes:
        - name: eventstreams-pem-certificate
          secret:
            secretName: "{{ .Values.eventstreams.caPemSecretName }}"
      {{- end }}
